export { default as BasketPage } from './BasketPage/BasketPage'
export { default as CataloguePage } from './CataloguePage/CataloguePage'
export { default as HomePage } from './HomePage/HomePage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage'
export { default as RegisterPage } from './RegisterPage/RegisterPage'